#!/usr/bin/env bash

# Check user environment variable
if [[ -z "${FIRESTORE_PROJECT_ID}" ]]; then
  echo "Missing FIRESTORE_PROJECT_ID environment variable" >&2
  exit 1
fi

if [[ -z "${FIRESTORE_HOST_PORT}" ]]; then
   FIRESTORE_HOST_PORT="0.0.0.0:8080"
fi

# Config gcloud project
gcloud config set project ${FIRESTORE_PROJECT_ID}

# Start emulator
gcloud beta emulators firestore start --host-port=$FIRESTORE_HOST_PORT --verbosity="debug" --project ${FIRESTORE_PROJECT_ID}
