version: 2
jobs:
  build:
    docker:
      - image: mtranter/sbt-protoc:1.2.8_2.12
      - image: pathmotion/firestore-emulator-docker:latest
        environment:
          FIRESTORE_PROJECT_ID: project-test
    working_directory: ~/fs2-firestore
    steps:
      - checkout
      - restore_cache:
          keys:
            - ivy
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          command: |
            echo $GCP_CREDENTIALS_64 | base64 -d > ~/fs2-firestore/gcp_creds.json
            export GCP_CREDENTIALS="~/fs2-firestore/gcp_creds.json"
            export GCP_PROJECT=test-firestore-fs2
            sbt ";set Global / patchVersion := Some(\"$CIRCLE_BUILD_NUM\");coverage;test;it:test;coverageReport;publish;writeVersion"
      - run: git tag $(cat ./version.txt) && git push --tags
      - save_cache:
          key: ivy
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: release
          filters:
            tags:
              ignore: /.*/
